---

- name: Create EC2 Instance
  ec2:
    aws_access_key: "{{amazon_aws_access_key}}"
    aws_secret_key: "{{amazon_aws_secret_key}}"
    key_name: "{{amazon_ssh_key_id}}"
    instance_type: "{{ec2_instance_type}}"
    image: "{{ec2_image}}"
    region: "{{ec2_region_id}}"
    vpc_subnet_id: "{{ec2_vpc_subnet_id}}"
    group_id: "{{ec2_security_group}}"
    wait: yes
    assign_public_ip: yes
  when: do_ssh_key_id is defined
  register: ec2


- name: Add new host to Ansible inventory
  add_host:
    hostname: "{{item.public_ip}}"
    groupname: amazon_ec2_hosts
  with_items: "{{ec2.instances}}"


- name: Wait for SSH to come up
  wait_for:
    host: "{{item.public_dns_name}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ec2.instances}}"

- pause:
    seconds: 15

