---
- name: Wait for SSH to come up
  wait_for:
    host: "{{item}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{hosts_to_check}}"
  when: hosts_to_check is defined

- name: Wait for SSH to come up
  wait_for:
    host: "{{host_to_check}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  when: host_to_check is defined

- pause:
    seconds: 15