---
# This playbook deploys the whole application stack in this site.

- name: Amazon EC2 VM
  remote_user: root
  hosts: localhost
  roles:
    - amazon-ec2
    #- { role: ssh-available, hosts_to_check: "{{ec2.instances[0].public_dns_name}}" }
    - { role: ssh-available, hosts_to_check: "{{groups['amazon_ec2_hosts']}}" }
    
- name: Plesk install to Amazon EC2
  remote_user: "{{ec2_remote_ssh_user}}"
  become_user: root
  hosts: amazon_ec2_hosts
  roles:
    - plesk-install
    - plesk-configure
    - plesk-get-access