---
# This playbook deploys the whole application stack in this site.

- name: Amazon EC2 VM
  remote_user: root
  hosts: localhost
  roles:
    - amazon-ec2

- name: Plesk install to Amazon EC2
  remote_user: root
  hosts: amazon_ec2_hosts
  roles:
    - plesk-typical