---
# This playbook deploys the whole application stack in this site.

- name: Amazon EC2 VM
  remote_user: ec2-user
  hosts: localhost
  roles:
    - amazon-ec2
    - { role: ssh-available, hosts_to_check: "{{groups['amazon_ec2_hosts']}}" }
    #- { role: ssh-available, host_to_check: "{{ec2.instances[0].public_dns_name}}" }
    