---
# This playbook deploys the whole application stack in this site.

- name: Amazon EC2 VM
  remote_user: ec2-user
  hosts: localhost
  roles:
    - amazon-ec2
    - { role: ssh-available, hosts_to_check: "{{groups['amazon_ec2_hosts']}}", ssh_delay: 100, ssh_timeout: 600 }
    #- { role: ssh-available, host_to_check: "{{ec2.instances[0].public_dns_name}}" }

- name: Configure Plesk
  remote_user: "{{ec2_remote_ssh_user}}"
  become_user: root
  hosts: amazon_ec2_hosts
    - plesk-configure
    - plesk-get-access